[workspace]
members = [
    "src/time_capsule_backend"
]
resolver = "2"

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

[workspace.dependencies]
candid = "0.8"
ic-cdk = "0.7"
ic-cdk-macros = "0.6"
serde = "1.0"